{
    'name': 'Gestion d\'Association',
    'version': '1.0',
    'category': 'Associations',
    'summary': 'Gérer les membres et les événements de l\'association',
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'views/member_views.xml',
        'views/event_views.xml',
        'views/dashboard_views.xml',
        'views/receipt_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'test': [
        'tests/test_member.py',
        'tests/test_event.py',
        'tests/test_receipt.py',
        'tests/test_views.py',
    ],
}